server:
  port: 8090

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  #    This is to tell spring that we have two more profiles
  config:
    import:
      - "application_qa.yml"
      - "application_prod.yml"
  #    This is to tell spring that active the below profile when loading
  # so spring boot will check every property and see what properties are overridden the rest properties it will take from the default yml file
  profiles:
    active:
      - "qa"

build:
  version: "10.0"

loans:
  message: "Welcome to Rakesh Bank loans related local APIs "
  contactDetails:
    name: "John Doe - Developer"
    email: "john@rakeshbank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345