
build:
  version: "9.0"

accounts:
  message: "Welcome to Rakesh Bank accounts related prod APIs"
  contactDetails:
    name: "Rene copo- Product Owner"
    email: "rene@rakeshbank.com"
  onCallSupport:
    - (453) 392-4829
    - (236) 203-0385