
build:
  version: "3.0"

cards:
  message: "Welcome to Rakesh Bank cards related local APIs "
  contactDetails:
    name: "John Doe - Developer"
    email: "john@rakeshbank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345