
build:
  version: "4.0"

cards:
  message: "Welcome to Rakesh Bank cards related QA APIs"
  contactDetails:
    name: "Smitha Ray- QA Lead"
    email: "smitha@rakeshbank.com"
  onCallSupport:
    - (666) 265-3765
    - (666) 734-8371