#Here we are telling spring, when to activate this yml file
spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0"

accounts:
  message: "Welcome to Rakesh Bank accounts related QA APIs"
  contactDetails:
    name: "Smitha Ray- QA Lead"
    email: "smitha@rakeshbank.com"
  onCallSupport:
    - (666) 265-3765
    - (666) 734-8371