#Here we are telling spring, when to activate this yml file
spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

accounts:
  message: "Welcome to Rakesh Bank accounts related prod APIs"
  contactDetails:
    name: "Rene copo- Product Owner"
    email: "rene@rakeshbank.com"
  onCallSupport:
    - (453) 392-4829
    - (236) 203-0384