server:
  port: 8080

spring:
  application:
    name: "accounts"
  profiles:
    active: "prod"
  datasource:
    url: jdbc:mysql://localhost:3307/accountsdb
    username: root
    password: password
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
    #    This tells springboot where is our config server located
    #  When we do some configuration changes in github while our services are running, then to reflect those changes
    #  we have to enable actuator endpoints in the service and hit one specific endpoint called refresh
    #  eg:- http://localhost:9000/actuator/refresh is the endpoint for this service
  #  this is not a feasible option because lets say if we have many instances of our service then we have to refresh all
  #  the instances. hence we will use spring bus which uses rabbit mq like below
  config:
    import: "optional:configserver:http://localhost:8071/"
  #Here we wanted to refresh all the instances of our service so that they can fetch the latest config file from github
  #We can do it manually by hitting refresh endpoints of each service instances, but the better way is using spring cloud
  #bus, run the rabbitmq (docker run -it --rm --name rabbitmq -p 5672:5672 -p 15672:15672 rabbitmq:3.12-management),
  #then add the dependency of cloud bus in pom.xml and add he below rabbitmq properties and
  #invoke the busrefresh api given by actuator on any running service, this endpoint will fetch the latest config file
  #for all the instances of all other services too, just that all other instances should also register on the same
  #  rabbitmq
  #  rabbitmq:
  #    host: "localhost"
  #    port: 5672
  #    stream:
  #      username: "guest"
  #      password: "guest"

  #This will enable all the endpoints given by the actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true


endpoints:
  shutdown:
    enabled: true


eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8070/eureka/

#This info will be shown on the eureka dashboard for this service
info:
  app:
    name: "accounts"
    description: "Rakesh Bank Account Application"
    version: "1.0.0"

logging:
  level:
    com:
      rakesh:
        accounts: DEBUG
